# Generated by Django 2.1.2 on 2018-12-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landresource',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='创建日期'),
        ),
    ]
