# Generated by Django 2.1.2 on 2018-12-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181224_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingresource',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='plantresource',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='storeresource',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='landresource',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建日期'),
        ),
    ]
