# Generated by Django 2.1.2 on 2018-12-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181224_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='result',
            field=models.CharField(blank=True, choices=[('0', '不通过'), ('1', '通过'), ('2', '退回'), ('3', '未处理')], max_length=2, null=True, verbose_name='结果'),
        ),
    ]
